[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/content/*"
  to = "/content/:splat"
  status = 200


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[redirects]]
  from = "/gallery/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/events/*"
  to = "/index.html"
  status = 200