backend:
  name: git-gateway
  branch: main
  site_domain: martial-arts-silambam.netlify.app  # Your site URL

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "events"
    label: "Events"
    folder: "src/content/events"
    create: true
    slug: "{{slug}}"
    format: "json" 
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Type", name: "type", widget: "select", 
          options: ["workshop", "competition", "seminar", "webinar"],
          default: "workshop" }